### ISSUE TITLE
poj

### ISSUE THREAD

**Issue by cck7202** [SullivanNorthHS/AnnouncementBuddy#15]
Great App. Wonderful!

**Comment by cck7202** [comment]
you need to change the color to blue and black-just a opinion

**Comment by cck7202** [comment]
or a thought

**Comment by cck7202** [comment]
its a good colors

**Comment by snhs-r3c0n** [comment]
Need is an overstatement. Our team is happy with the current colors of this application.

**Comment by cck7202** [comment]
well im not

**Comment by cck7202** [comment]
im sorry
